services:
  - type: web
    name: task-manager-api
    runtime: python
    pythonVersion: 3.13
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn run:app --bind 0.0.0.0:$PORT